image: Visual Studio 2019
skip_commits:
  message: /Merge pull request.*/
build_script:
- ps: >-
    dotnet build BasicFodyAddin --configuration Release

    dotnet test BasicFodyAddin --configuration Release --no-build --no-restore
test: off
artifacts:
- path: nugets\*.nupkg